import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Leftside from '../components/Leftside'
import Rightside from '../components/Rightside'
import Feed from "../components/Feed"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Twitter-Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./assets/Twitter.png" />
      </Head>

     <div className='flex'>

      {/* Left Part -> Home Search etc */}
        <Leftside />
      
      {/* Feed*/}

        <Feed />

      {/* Right Part -> Follow etc */}

      <Rightside/>

     </div>
    </div>
  )
}
